/* 실습과제 186 1번 */
SELECT DEPTNO, TRUNC(AVG(SAL)) AS AVG_SAL, MAX(SAL) AS MAS_SAL, MIN(SAL) AS MIN_SAL, COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO DESC

/* 실습과제 186 2번 */
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3

/* 실습과제 186 3번 */
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_DATE, DEPTNO, COUNT(*) CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO

/* 실습과제 187 4번 */
SELECT NVL2(COMM, 'Y', 'N') AS EXIST_COMM,
       COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM, 'Y', 'N')

SELECT * FROM EMP

/* 실습과제 187 5번 */
SELECT DEPTNO, TO_CHAR(HIREDATE, 'YYYY') AS HIRE_DATE, COUNT(*) AS CNT, MAX(SAL) AS MAX_SAL, SUM(SAL) AS SUM_SAL, AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY ROLLUP (DEPTNO, TO_CHAR(HIREDATE, 'YYYY'))

SELECT *
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
ORDER BY EMPNO

SELECT *
FROM EMP E JOIN DEPT D USING (DEPTNO)
ORDER BY E.EMPNO

SELECT E1.EMPNO
    , E1.ENAME
    , E1.MGR
    , E2.EMPNO AS MGR_EMPNO
    , E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO

SELECT E1.EMPNO
    , E1.ENAME
    , E1.MGR
    , E2.EMPNO AS MGR_EMPNO
    , E2.ENAME AS MGR_ENAME
FROM EMP E1 LEFT OUTER JOIN EMP E2
    ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO

SELECT E1.EMPNO
    , E1.ENAME
    , E1.MGR
    , E2.EMPNO AS MGR_EMPNO
    , E2.ENAME AS MGR_ENAME
FROM EMP E1 RIGHT OUTER JOIN EMP E2
    ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO

SELECT * FROM EMP

SELECT * FROM DEPT

SELECT D.DEPTNO
    , E.JOB AS DNAME
    , E.EMPNO
    , E.ENAME
    , E.SAL
FROM EMP E JOIN DEPT D ON E.SAL > 2000
ORDER BY D.DEPTNO, E.JOB ASC

SELECT D.DEPTNO
    , E.JOB AS DNAME
    , E.EMPNO
    , E.ENAME
    , E.SAL
FROM EMP E, DEPT D
WHERE E.SAL > 2000
ORDER BY D.DEPTNO, E.JOB ASC

SELECT *
FROM EMP E JOIN DEPT D ON(E.DEPTNO = D.DEPTNO)
ORDER BY EMPNO

SELECT E.DEPTNO
    , D.DNAME
    , FLOOR(AVG(E.SAL)) AS AVG_SAL
    , MAX(E.SAL) AS MAX_SAL
    , MIN(E.SAL) AS MIN_SAL
    , COUNT(E.DEPTNO) AS CNT
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO, D.DNAME
ORDER BY E.DEPTNO, D.DNAME

SELECT * FROM EMP

SELECT * FROM DEPT

SELECT E.DEPTNO
    , D.DNAME
    , E.EMPNO
    , E.ENAME
    , E.JOB
    , E.SAL
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
ORDER BY E.DEPTNO, D.DNAME

SELECT D.DEPTNO AS DEPTNO
    , D.DNAME
    , E.EMPNO
    , E.ENAME
    , E.MGR
    , E.SAL
    , E.DEPTNO AS DEPTNO
    , S.LOSAL
    , S.HISAL
    , S.GRADE
    , E2.EMPNO AS MGR_EMPNO
    , E2.ENAME AS MGR_ENAME
FROM EMP E RIGHT JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
LEFT OUTER JOIN SALGRADE S ON (E.SAL >= S.LOSAL AND E.SAL <= S.HISAL)
LEFT OUTER JOIN EMP E2 ON (E.MGR = E2.EMPNO)
ORDER BY D.DEPTNO, E.EMPNO



WHERE E.DEPTNO(+) = D.DEPTNO
AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
AND E.MGR = E2.EMPNO(+)
ORDER BY D.DEPTNO, E.EMPNO

SELECT * FROM SALGRADE

SELECT D.DEPTNO AS DEPTNO
    , D.DNAME
    , E.EMPNO
    , E.ENAME
    , E.MGR
    , E.SAL
    , E.DEPTNO AS DEPTNO
    , S.LOSAL
    , S.HISAL
    , S.GRADE
    , E2.EMPNO AS MGR_EMPNO
    , E2.ENAME AS MGR_ENAME
FROM EMP E RIGHT JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
LEFT OUTER JOIN SALGRADE S ON (E.SAL >= S.LOSAL AND E.SAL <= S.HISAL)
LEFT OUTER JOIN EMP E2 ON (E.MGR = E2.EMPNO)
ORDER BY D.DEPTNO, E.EMPNO

SELECT *
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE
                    FROM EMP
                    WHERE ENAME = 'BLAKE')

SELECT E.EMPNO
    , E.ENAME
    , E.JOB
    , E.SAL
    , D.DEPTNO
    , D.DNAME
    , D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
    AND E.DEPTNO = 20
    AND E.SAL > (SELECT AVG(SAL) FROM EMP)

SELECT * FROM EMP

SELECT * FROM DEPT

SELECT DEPTNO, ENAME, SAL
FROM EMP
WHERE SAL IN (SELECT MAX(SAL)
                FROM EMP
                GROUP BY DEPTNO)

SELECT DEPTNO, ENAME, SAL
FROM EMP
WHERE SAL = ANY (SELECT MAX(SAL)
                    FROM EMP
                    GROUP BY DEPTNO)

SELECT *
FROM EMP
WHERE SAL < ANY (SELECT SAL
                    FROM EMP
                    WHERE DEPTNO = 30)
ORDER BY SAL, EMPNO

SELECT *
FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
                            FROM EMP
                            GROUP BY DEPTNO)

SELECT DEPTNO, MAX(SAL)
                            FROM EMP
                            GROUP BY DEPTNO
SELECT E.EMPNO
    , E.ENAME
    , E.DEPTNO
    , D.DNAME
    , D.LOC
FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E
    , (SELECT * FROM DEPT) D
WHERE E.DEPTNO = D.DEPTNO

SELECT * FROM DEPT

SELECT * FROM EMP

SELECT E.JOB
    , E.EMPNO
    , E.ENAME
    , E.SAL
    , D.DEPTNO
    , D.DNAME
FROM DEPT D, EMP E
WHERE E.JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN')

SELECT * FROM EMP

SELECT E.EMPNO
    , E.ENAME
    , D.DNAME
    , E.HIREDATE
    , D.LOC
    , E.SAL
    , S.GRADE
FROM EMP E LEFT JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
INNER JOIN SALGRADE S ON (E.SAL >= S.LOSAL AND E.SAL <= S.HISAL)
AND E.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY GRADE DESC

SELECT E.EMPNO
    , E.ENAME
    , E.JOB
    , E.DEPTNO
    , D.DNAME
    , D.LOC
FROM EMP E, DEPT D
WHERE E.ENAME IN (SELECT ENAME FROM EMP WHERE DEPTNO = '10')
AND E.JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO = '30')

SELECT E.EMPNO
    , E.ENAME
    , E.JOB
    , E.DEPTNO
    , D.DNAME
    , D.LOC
FROM EMP E, DEPT D
WHERE E.SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'PRESIDENT')

SELECT E.EMPNO
    , E.ENAME
    , E.JOB
    , E.DEPTNO
    , D.DNAME
    , D.LOC
FROM EMP E, DEPT D
WHERE E.SAL > ALL (SELECT SAL FROM EMP WHERE JOB = 'PRESIDENT')

CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT

SELECT * FROM DEPT

DROP TABLE EMP_TEMP

SELECT * FROM EMP_TEMP

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01', 5000, 1000, 10)

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(2111, '이순신', 'MANAGER', NULL, '2003/02/03', 4000, NULL, 10)

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30)

SELECT * FROM EMP_TEMP

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE=1;

CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2

UPDATE DEPT_TEMP2
SET DNAME ='DATABASE', LOC='SEOUL'
WHERE DEPTNO = 40;

UPDATE EMP_TEST
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL) FROM EMP_TEST WHERE DEPTNO = 50)

SELECT * FROM EMP_TEST

UPDATE EMP_TEST
SET DEPTNO = 80, SAL = SAL * 1.2
WHERE (DEPTNO, SAL) IN
      (SELECT DEPTNO, SAL
        FROM (SELECT ROWNUM AS RN, DEPTNO, SAL
        FROM (SELECT DEPTNO, SAL
                FROM EMP_TEST
                WHERE DEPTNO = 30
                ORDER BY HIREDATE))
                WHERE RN > 1)


SELECT * FROM EMP_TEST
WHERE DEPTNO = 30

UPDATE DEPT_TEMP2
SET (DNAME, LOC) = (SELECT DNAME, LOC
                        FROM DEPT
                        WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2

UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE', LOC ='SEOUL'
WHERE DEPTNO = 40

UPDATE DEPT_TEMP2
SET DNAME = (SELECT DNAME
                FROM DEPT
                WHERE DEPTNO = 40),
    LOC = (SELECT LOC
                FROM DEPT
                WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'
WHERE DEPTNO = (SELECT DEPTNO
                    FROM DEPT_TEMP2
                    WHERE DNAME = 'OPERATIONS')

DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER'

DROP TABLE DEPT_TEST

CREATE TABLE DEPT_TEST AS SELECT * FROM DEPT

SELECT * FROM DEPT_TEST

INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(50, 'ORACLE', 'BUSAN')
INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(60, 'SQL', 'ILSAN')
INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(70, 'SELECT', 'INCHEON')
INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(80, 'DML', 'BUNDANG')

CREATE TABLE SCORE (
    SEQ INTEGER,
    NUM INT
)

SELECT * FROM SCORE

INSERT INTO SCORE(SEQ, NUM) VALUES (1, 10)
INSERT INTO SCORE(SEQ, NUM) VALUES (2, 20)
INSERT INTO SCORE(SEQ, NUM) VALUES (3, 30)
INSERT INTO SCORE(SEQ, NUM) VALUES (4, 40)
INSERT INTO SCORE(SEQ, NUM) VALUES (5, 50)


SELECT * FROM SCORE

SELECT * FROM EMP_TEST

SELECT NUM
    FROM (SELECT ROWNUM AS RN, NUM
            FROM (SELECT NUM
                        FROM SCORE
                        ORDER BY NUM DESC))
WHERE RN = 2
ORDER BY NUM ASC

SELECT DEPTNO, SAL, EMPNO, ENAME, JOB
FROM EMP_TEST

CREATE TABLE EMP_TEST AS SELECT * FROM EMP

SELECT * FROM EMP_TEST

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('2016-01-02 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 4500, 0, 20)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('2016-02-21 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 1800, 0, 10)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7203, 'TEST_USER3', 'ANALYST', 7201, TO_DATE('2016-04-11 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 3400)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('2016-05-31 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2700)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('2016-07-20 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2600)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('2016-09-08 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2600)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('2016-10-28 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2300)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('2018-03-09 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 1200)

CREATE TABLE EMP_NEW (
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
)

ALTER TABLE EMP_NEW ADD HP VARCHAR2(20)

ALTER TABLE EMP_NEW RENAME TO EMP_RENAME

SELECT * FROM EMP_NEW

SELECT * FROM EMP_RENAME

ALTER TABLE EMP_NEW RENAME COLUMN HP TO TEL;

ALTER TABLE EMP_NEW
MODIFY EMPNO NUMBER(5);

SELECT * FROM EMP_NEW

ALTER TABLE EMP_NEW DROP COLUMN TEL;

CREATE TABLE EMP_USER (
    EMPNO NUMBER(5),
    ENAME VARCHAR2(20),
    JOB VARCHAR2(10),
    MGR NUMBER(5),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    DEPTNO NUMBER
)

ALTER TABLE EMP_USER ADD RESIGN_DATE DATE

ALTER TABLE EMP_USER ADD DAY_DATE DATE

SELECT * FROM EMP_USER

ALTER TABLE EMP_USER ADD SUR_NAME CHAR(5)

ALTER TABLE EMP_USER RENAME COLUMN ENAME TO FULL_NAME;

SELECT * FROM EMP_USER

CREATE SEQUENCE SEQ_DEPTSEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE NOCACHE;

CREATE TABLE DEPTSEQ AS SELECT * FROM DEPT

SELECT * FROM DEPTSEQ

INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPTSEQ.NEXTVAL, 'DATABASE', 'SEOUL')

INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPTSEQ.NEXTVAL, 'WEB', 'BUSAN')

INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPTSEQ.NEXTVAL, 'MOBILE', 'ILSAN')

SELECT * FROM LOGIN

CREATE TABLE LOGIN(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
    TEL VARCHAR2(20)
)

SELECT OWNER
    , CONSTRAINT_NAME
    , CONSTRAINT_TYPE
    , TABLE_NAME
FROM USER_CONSTRAINTS

ALTER TABLE LOGIN2
MODIFY(TEL CONSTRAINT TBLNN_TEL_NN NOT NULL)

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'LOGIN2'

CREATE TABLE LOGIN_UNIQUE
(
    LOGIN_ID VARCHAR2(20) UNIQUE,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
)

INSERT INTO LOGIN_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES(NULL, 'PWD01', '010-2345-6788')

INSERT INTO LOGIN_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01', 'PWD01', '010-2345-6788')

SELECT * FROM LOGIN_UNIQUE

SELECT * FROM EMP

SELECT * FROM EMP_FK

CREATE TABLE EMP_FK
(
    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY
    , ENAME VARCHAR2(10)
    , JOB VARCHAR2(9)
    , MGR VARCHAR2(9)
    , HIREDATE DATE
    , SAL NUMBER(7,2)
    , COMM NUMBER(7,2)
    , DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
)


CREATE TABLE DEPT_FK
(
      DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY
    , DNAME VARCHAR2(14)
    , LOC VARCHAR2(13)
)

SELECT * FROM DEPT_FK

INSERT INTO LOGIN_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL) VALUES ('TEST_ID_01', 'PWD01', '010-1234-5678')

CREATE TABLE TABLE_CHECK (
      LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY
    , LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK(LENGTH(LOGIN_PWD)>3)
    , TEL VARCHAR2(20)
)

INSERT INTO TABLE_CHECK VALUES('TSET_ID', '1234', '010-1234-5678')

SELECT * FROM TABLE_CHECK

CREATE TABLE TABLE_DEFAULT (
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK2_LOGINID_PK PRIMARY KEY
    , LOGIN_PWD VARCHAR2(20) DEFAULT '1234'
    , TEL VARCHAR2(20)
)

INSERT INTO TABLE_DEFAULT
VALUES('TEST_ID', NULL, '010-1234-5678')

INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL)
VALUES('TEST_ID2', '010-1234-5678')

SELECT * FROM TABLE_DEFAULT
