/* 이론과제 2일차
    1-1. 테이블
    1-2. 외래 키
    1-3. 널

    2-1. 문자셋
    2-2. 문자셋

    3-1. VARCHAR2
    3-2. CHAR

    4-1. 제약 조건
    4-2. 기본키
    4-3. 외래키

    5-1. 무결성
    5-2. 무결성
    5-3. 무결성

    6-1. unique
    6-2. not null
    6-3. index
 */

/* 실습과제 186 1번 */
SELECT DEPTNO, TRUNC(AVG(SAL)) AS AVG_SAL, MAX(SAL) AS MAS_SAL, MIN(SAL) AS MIN_SAL, COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO DESC

/* 실습과제 186 2번 */
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3

/* 실습과제 186 3번 */
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_DATE, DEPTNO, COUNT(*) CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO

/* 실습과제 187 4번 */
SELECT NVL2(COMM, 'Y', 'N') AS EXIST_COMM,
       COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM, 'Y', 'N')

SELECT * FROM EMP

/* 실습과제 187 5번 */
SELECT DEPTNO, TO_CHAR(HIREDATE, 'YYYY') AS HIRE_DATE, COUNT(*) AS CNT, MAX(SAL) AS MAX_SAL, SUM(SAL) AS SUM_SAL, AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY ROLLUP (DEPTNO, TO_CHAR(HIREDATE, 'YYYY'))

/* 실습과제 198 1번*/
SELECT D.DEPTNO
    , E.JOB AS DNAME
    , E.EMPNO
    , E.ENAME
    , E.SAL
FROM EMP E JOIN DEPT D ON E.SAL > 2000
ORDER BY D.DEPTNO, E.JOB ASC

SELECT D.DEPTNO
    , E.JOB AS DNAME
    , E.EMPNO
    , E.ENAME
    , E.SAL
FROM EMP E, DEPT D
WHERE E.SAL > 2000
ORDER BY D.DEPTNO, E.JOB ASC

/* 실습과제 198 2번*/
SELECT E.DEPTNO
    , D.DNAME
    , FLOOR(AVG(E.SAL)) AS AVG_SAL
    , MAX(E.SAL) AS MAX_SAL
    , MIN(E.SAL) AS MIN_SAL
    , COUNT(E.DEPTNO) AS CNT
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO, D.DNAME
ORDER BY E.DEPTNO, D.DNAME

/* 실습과제 199 3번*/
SELECT E.DEPTNO
    , D.DNAME
    , E.EMPNO
    , E.ENAME
    , E.JOB
    , E.SAL
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
ORDER BY E.DEPTNO, D.DNAME

/* 실습과제 199 4번*/
SELECT D.DEPTNO AS DEPTNO
    , D.DNAME
    , E.EMPNO
    , E.ENAME
    , E.MGR
    , E.SAL
    , E.DEPTNO AS DEPTNO
    , S.LOSAL
    , S.HISAL
    , S.GRADE
    , E2.EMPNO AS MGR_EMPNO
    , E2.ENAME AS MGR_ENAME
FROM EMP E RIGHT JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
LEFT OUTER JOIN SALGRADE S ON (E.SAL >= S.LOSAL AND E.SAL <= S.HISAL)
LEFT OUTER JOIN EMP E2 ON (E.MGR = E2.EMPNO)
ORDER BY D.DEPTNO, E.EMPNO

/* 실습과제 210 1번*/
SELECT E.JOB
    , E.EMPNO
    , E.ENAME
    , E.SAL
    , D.DEPTNO
    , D.DNAME
FROM DEPT D, EMP E
WHERE E.JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN')

/* 실습과제 210 2번*/
SELECT E.EMPNO
    , E.ENAME
    , D.DNAME
    , E.HIREDATE
    , D.LOC
    , E.SAL
    , S.GRADE
FROM EMP E LEFT JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
INNER JOIN SALGRADE S ON (E.SAL >= S.LOSAL AND E.SAL <= S.HISAL)
AND E.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY GRADE DESC

/* 실습과제 211 3번*/
SELECT E.EMPNO
    , E.ENAME
    , E.JOB
    , E.DEPTNO
    , D.DNAME
    , D.LOC
FROM EMP E, DEPT D
WHERE E.ENAME IN (SELECT ENAME FROM EMP WHERE DEPTNO = '10')
AND E.JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO = '30')

/* 실습과제 211 4번*/
SELECT E.EMPNO
    , E.ENAME
    , E.JOB
    , E.DEPTNO
    , D.DNAME
    , D.LOC
FROM EMP E, DEPT D
WHERE E.SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'PRESIDENT')

/* 실습과제 211 5번*/
SELECT E.EMPNO
    , E.ENAME
    , E.JOB
    , E.DEPTNO
    , D.DNAME
    , D.LOC
FROM EMP E, DEPT D
WHERE E.SAL > ALL (SELECT SAL FROM EMP WHERE JOB = 'PRESIDENT')

/* 실습과제 222 1번*/
CREATE TABLE DEPT_TEST AS SELECT * FROM DEPT

SELECT * FROM DEPT_TEST

INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(50, 'ORACLE', 'BUSAN')
INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(60, 'SQL', 'ILSAN')
INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(70, 'SELECT', 'INCHEON')
INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC) VALUES(80, 'DML', 'BUNDANG')

/* 실습과제 222 2번*/
CREATE TABLE EMP_TEST AS SELECT * FROM EMP

SELECT * FROM EMP_TEST

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('2016-01-02 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 4500, 0, 20)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('2016-02-21 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 1800, 0, 10)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7203, 'TEST_USER3', 'ANALYST', 7201, TO_DATE('2016-04-11 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 3400)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('2016-05-31 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2700)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('2016-07-20 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2600)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('2016-09-08 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2600)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('2016-10-28 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 2300)

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
VALUES (7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('2018-03-09 00:00:00', 'YYYY-DD-MM HH24:MI:SS'), 1200)

/* 실습과제 223 3번*/
UPDATE EMP_TEST
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL) FROM EMP_TEST WHERE DEPTNO = 50)

/* 실습과제 223 4번*/
UPDATE EMP_TEST
SET DEPTNO = 80, SAL = SAL * 1.2
WHERE (DEPTNO, SAL) IN
      (SELECT DEPTNO, SAL
        FROM (SELECT ROWNUM AS RN, DEPTNO, SAL
        FROM (SELECT DEPTNO, SAL
                FROM EMP_TEST
                WHERE DEPTNO = 30
                ORDER BY HIREDATE))
                WHERE RN > 1)

/* 실습과제 228 1번 */
CREATE TABLE EMP_USER (
    EMPNO NUMBER(5),
    ENAME VARCHAR2(20),
    JOB VARCHAR2(10),
    MGR NUMBER(5),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    DEPTNO NUMBER
)

/* 실습과제 228 2번 */
ALTER TABLE EMP_USER ADD RESIGN_DATE DATE
ALTER TABLE EMP_USER ADD DAY_DATE DATE

/* 실습과제 228 3번 */
ALTER TABLE EMP_USER ADD SUR_NAME CHAR(5)

/* 실습과제 228 4번 */
ALTER TABLE EMP_USER MODIFY SUR_NAME CHAR(10)

/* 실습과제 228 5번 */
ALTER TABLE EMP_USER RENAME COLUMN ENAME TO FULL_NAME

/* 실습과제 242 이론문제
 1. 제약조건
 2. UNIQUE
 3. NOT NULL
 4. PRIMARY KEY
 5. 외래키
 */

/* 실습과제 249 1번 */
CREATE TABLE EMP_IDX AS SELECT * FROM EMP

CREATE INDEX EMP_EMPNO_IDX ON EMP_IDX(EMPNO)

/* 실습과제 249 2번 */
SELECT INDEX_NAME, TABLE_NAME, TABLESPACE_NAME
FROM USER_INDEXES
WHERE TABLE_NAME = 'EMP_IDX'

SELECT * FROM EMP_IDX

/* 실습과제 249 3번 */
CREATE VIEW VW_EMP_IDX
AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL, CASE WHEN COMM IS NOT NULL THEN 'Y' ELSE 'N' END AS COMM
        FROM EMP_IDX
        WHERE SAL >= 20000)

SELECT * FROM VW_EMP_IDX